services:
  php:
    build:
      context: ./images/php-fpm
    volumes:
      - ./app:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy

  nginx:
    build:
      context: ./images/nginx
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - php

  mariadb:
    image: mariadb:11.3
    environment:
      MARIADB_ROOT_PASSWORD: "root"
      MARIADB_DATABASE: "e_commerce"
      MARIADB_USER: "test"
      MARIADB_PASSWORD: "1123."
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 3

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mariadb_data:
  redis_data:
