nelmio_api_doc:
    documentation:
        info:
            title: Order Platform
            description: Order & Campaign API
            version: 1.0.0
        components:
            securitySchemes:
                ApiKey:
                    type: apiKey
                    in: header
                    name: X-AUTH-TOKEN
        security:
            - ApiKey: []
    areas:
        path_patterns:
            - ^/api(?!/doc) # /api altındaki tüm rotalar, /api/doc hariç
