security:
    providers:
        api_user_provider:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        main:
            lazy: true
            stateless: true
            custom_authenticators:
                - App\Security\ApiKeyAuthenticator

    access_control:
        - { path: ^/api/doc, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: ROLE_API }
